#!/bin/bash

GRPE=${1}
SALLE=${2:-$(salle)}
etudiants ${GRPE} >/dev/null || { echo "Error: Groupe Inexistant"; exit 1; }
LOGINS=$(etudiants ${GRPE})

for etu in ${LOGINS}
do
    if ( ! est-connecte-dans ${etu} )
    then
        identite ${etu}
    fi
done
exit 0
