#!/bin/bash

pareil $# 0 && { echo "Error: login obligatoire"; exit 1; }

if pareil $1 "-m"
then
    LOGIN=${2}
    lasalle=${3:-$(salle)}
    SHOW=1;
else
    LOGIN=${1}
    lasalle=${2:-$(salle)}
    SHOW=0
fi

for pc in $(machines ${lasalle})
do
    if est-connecte-sur ${LOGIN} ${pc}
    then
        pareil ${SHOW} 1  && echo "${LOGIN} est connecté sur ${pc}"
        exit 0
    fi
done
