#!/bin/bash
echo "a = a   : " $(pareil a a       && echo ok)
echo "ab = ab : " $(pareil ab ab     && echo ok)
echo "1 = 1   : " $(pareil 1 1       && echo ok)
echo "-e = -e : " $(pareil -e -e     && echo ok)
echo "a = ab  : " $(pareil a ab      || echo ko)
echo "a = b   : " $(pareil a b       || echo ko)
echo "ab = a  : " $(pareil ab a      || echo ko)
